### ISSUE TITLE
Compatibility with python 3.7+

### ISSUE THREAD

**Issue by cthoyt** [aida-ugent/CSNE#7]
Python 2.7 is way past end-of-life and Python 3.6 will be at end of life at the end of the year. Are there specific reasons why you pinned the repository to older versions of python as well as pretty old versions of its dependencies?

It says on the README now that the code is extensively tested but I'm not really sure what this means without having something like unittests that can be run programatically. If testing were possible programatically, you could show that it's compatible with more modern versions of python and the dependent libraries

**Comment by Dru-Mara** [comment]
I am aware of the end of life of Py2 and yes, there are reasons for the changes I've made. I've run hundreds of experiments using this specific setup of CSNE in python2 and with the exact dependencies mentioned, so I am confident it works as it should. Also, the results in the paper, which I want to make sure everyone can replicate, were obtained using EvalNE and CSNE under python2. 

I've tried to replicate those same results from the paper with a range of different python versions, from 3.6 to 3.8 and they all gave me inconsistent results, sometimes better, sometimes worse. It would be nice to investigate why that is hapening, but I just don't have the time. 

Also, I fucking hate python 3 XD
